name: Client Side Tools - Spotbugs

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      

      - name: Send Client Side Tools and Coverage Results - 
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          export CODACY_CODE=$GITHUB_WORKSPACE
          docker run \
            --rm=true \
            --env CODACY_CODE="$CODACY_CODE" \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --volume "$CODACY_CODE":"$CODACY_CODE" \
            --volume /tmp:/tmp \
            codacy/codacy-analysis-cli \
              analyze --tool spotbugs --upload --project-token ${{ secrets.CODACY_PROJECT_TOKEN }} --max-allowed-issues 99999 --commit-uuid $GITHUB_SHA

